CREATE TABLE CB_IMAGE (
  ID            BIGINT        NOT NULL AUTO_INCREMENT,
  IMAGE_AUTHOR  BIGINT        NOT NULL,
  IMAGE_NAME    VARCHAR(100)  NOT NULL,
  IMAGE_TYPE    VARCHAR(100)  NOT NULL,
  IMAGE_DATA    LONGBLOB      NOT NULL,
  RECIPE_ID     BIGINT,

  foreign key FK_USER_ID (IMAGE_AUTHOR)  references CB_USER (ID),
  foreign key FK_RECIPE_ID_2 (RECIPE_ID) references CB_RECIPE (ID),

  CONSTRAINT PK_IMAGE PRIMARY KEY (ID)
)