CREATE TABLE CB_RECIPE (
  ID          BIGINT        NOT NULL AUTO_INCREMENT,
  NAME        VARCHAR(100)  NOT NULL,
  USER_ID     BIGINT        NOT NULL,
  SERVINGS    INT           NOT NULL,
  DESCRIPTION VARCHAR(1000) NOT NULL,
  CATEGORY_ID BIGINT        NOT NULL,
  foreign key FK_RECIPE_USER (USER_ID) references CB_USER (ID),

  CONSTRAINT PK_RECIPE PRIMARY KEY (ID)
)