CREATE TABLE CB_INGREDIENT (
  ID        BIGINT       NOT NULL AUTO_INCREMENT,
  AMOUNT    DOUBLE       NOT NULL,
  UNIT      VARCHAR(30)  NOT NULL,
  NAME      VARCHAR(100) NOT NULL,
  RECIPE_ID BIGINT,
  foreign key FK_RECIPE_ID (RECIPE_ID) references CB_RECIPE (ID),

  CONSTRAINT PK_INGREDIENT PRIMARY KEY (ID)
)