CREATE TABLE CB_USER (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  FIRST_NAME VARCHAR(100) NOT NULL,
  LAST_NAME VARCHAR(100) NOT NULL,
  EMAIL VARCHAR(100) NOT NULL,
  KEYCLOAK_USER_ID VARCHAR(50) NOT NULL,

  CONSTRAINT PK_USER PRIMARY KEY(ID)
)