CREATE TABLE CB_RECIPE (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  NAME VARCHAR(100) NOT NULL,
  USER_ID BIGINT NOT NULL,
  IMAGE_URL VARCHAR(300),
  SERVINGS INT NOT NULL,
  DESCRIPTION VARCHAR(1000) NOT NULL,
  CATEGORY_ID BIGINT NOT NULL,

  CONSTRAINT PK_RECIPE PRIMARY KEY(ID),
  CONSTRAINT FK_RECIPE_USER FOREIGN KEY(USER_ID) REFERENCES CB_USER(ID)
)